src/anygram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.views.generic.base import TemplateView

handler404 = "anygram.views.page_not_found" # noqa
handler500 = "anygram.views.server_error" # noqa

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('recipes.urls')),
    path('api/', include('api.urls')),
    path('cart/', include('cart.urls')),
    path('about/author/', TemplateView.as_view(
        template_name='about/author.html'
    ), name='about_author'),
    path('about/tech/', TemplateView.as_view(
        template_name='about/technologies.html'
    ), name='about_tech'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

src/api/urls.py
from django.urls import include, path

from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register('follow', views.FollowView, basename='follow')
router.register('favorites', views.FavoriteView, basename='favorites')
router.register('purchases', views.PurchasesView, basename='purchases')
router.register('ingredients', views.IngredientsView, basename='ingredients')

urlpatterns = [
    path('v1/', include(router.urls)),
]

src/recipes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.RecipeListView.as_view(), name='index'),
    path('recipe/new/', views.RecipeCreateView.as_view(),
         name='recipe_new'),
    path('recipe/<slug:slug>/', views.RecipeSingleView.as_view(),
         name='recipe'),
    path('recipe/<slug:slug>/edit/', views.RecipeUpdateView.as_view(),
         name='recipe_edit'),
    path('recipe/author/<str:username>/',
         views.RecipeAuthorListView.as_view(), name='index_author'),
    path('follow/', views.FollowListView.as_view(), name='index_follow'),
    path('favorites/', views.FavoriteListView.as_view(), name='favorites'),
]

src/recipes/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from pytils.translit import slugify

User = get_user_model()


class Tag(models.Model):
    class Colors(models.TextChoices):
        ORANGE = 'badge badge_style_orange'
        GREEN = 'badge badge_style_green'
        PURPLE = 'badge badge_style_purple'

    title = models.CharField('название тега', max_length=30)
    slug = models.SlugField(unique=True)
    color = models.CharField(
        'выберите цвет тега',
        max_length=30, choices=Colors.choices, default=Colors.PURPLE
    )

    class Meta:
        verbose_name = 'тег'
        verbose_name_plural = 'теги'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class Ingredient(models.Model):
    title = models.CharField('название ингредиента', max_length=50)
    slug = models.SlugField(unique=True)
    dimension = models.CharField('единицы измерения',
                                 max_length=15, default='шт.')

    class Meta:
        verbose_name = 'ингредиент'
        verbose_name_plural = 'ингредиенты'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='recipes',
                               verbose_name='автор рецепта')
    title = models.CharField('название рецепта', max_length=100, unique=True)
    slug = models.SlugField(unique=True)
    description = models.TextField('описание рецепта')
    duration = models.PositiveSmallIntegerField('время приготовления, мин')
    pub_date = models.DateTimeField('дата публикации', auto_now_add=True,
                                    db_index=True)
    image = models.ImageField('изображение рецепта', upload_to='recipes/',
                              blank=True, null=True)
    ingredients = models.ManyToManyField(
        Ingredient, through='RecipeIngredient', blank=True,
        verbose_name='ингредиенты для рецепта'
    )
    tags = models.ManyToManyField(
        Tag, related_name='recipes', blank=True,
        verbose_name='теги для рецепта'
    )
    in_favorite = models.ManyToManyField(
        User, related_name='favorites', blank=True,
        verbose_name='в избранном пользователей'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'рецепт'
        verbose_name_plural = 'рецепты'

    def __str__(self) -> str:
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('recipe', args=[str(self.slug)])

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    amount = models.PositiveSmallIntegerField('количество для приготовления')

    class Meta:
        verbose_name = 'данные об ингредиенте'
        verbose_name_plural = 'данные об ингредиентах'

src/recipes/forms.py
from django import forms

from .models import Recipe, RecipeIngredient


class RecipeCreateForm(forms.ModelForm):
    title = forms.CharField(initial='Название рецепта')
    duration = forms.IntegerField(initial=30)
    description = forms.CharField(
        widget=forms.Textarea(), initial='Последовательность приготовления'
    )

    class Meta:
        model = Recipe
        fields = ('title', 'description', 'duration',
                  'image', 'ingredients', 'tags')


class RecipeIngredientForm(forms.ModelForm):
    title = forms.CharField()

    class Meta:
        model = RecipeIngredient
        fields = ('amount', 'title')


IngredientFormSet = forms.inlineformset_factory(
    Recipe, RecipeIngredient, fields=('ingredient', 'amount')
)

src/recipes/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from recipes.forms import IngredientFormSet, RecipeCreateForm

from .models import Recipe, RecipeIngredient
from .utils import filter_by_tags

User = get_user_model()


class RecipeListView(ListView):
    paginate_by = 9
    template_name = 'recipes/recipe_index.html'

    def get_queryset(self):
        queryset = Recipe.objects.all()
        queryset, self.filter_tags = filter_by_tags(self.request, queryset)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Все рецепты Anygram'
        context['tags'] = self.filter_tags
        return context


class RecipeAuthorListView(ListView):
    paginate_by = 9
    template_name = 'recipes/recipe_author.html'

    def get_author(self):
        author = get_object_or_404(User, username=self.kwargs.get('username'))
        return author

    def get_queryset(self):
        queryset = Recipe.objects.filter(author=self.get_author())
        queryset, self.filter_tags = filter_by_tags(self.request, queryset)
        return queryset

    def get_context_data(self, **kwargs):
        author = self.get_author()
        context = super().get_context_data(**kwargs)
        context['title'] = f'Рецепты автора {author.first_name}'
        context['id'] = author.pk
        context['tags'] = self.filter_tags
        return context


class RecipeSingleView(DetailView):
    queryset = Recipe.objects.all()
    template_name = 'recipes/recipe_single.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recipeingredients'] = RecipeIngredient.objects.filter(
            recipe=self.get_object()
        )
        context['tags'] = self.get_object().tags.all()
        return context


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    form_class = RecipeCreateForm
    template_name = 'recipes/recipe_form.html'
    success_url = ''

    def get(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        ingredient_form = IngredientFormSet()
        return self.render_to_response(
            self.get_context_data(form=form,
                                  ingredient_form=ingredient_form)
        )

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        ingredient_form = IngredientFormSet(self.request.POST)
        if (form.is_valid() and ingredient_form.is_valid()):
            return self.form_valid(form, ingredient_form)
        else:
            return self.form_invalid(form, ingredient_form)

    def form_valid(self, form, ingredient_form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        ingredient_form.instance = self.object
        ingredient_form.instance.tags.set(form.cleaned_data.get('tags'))
        ingredient_form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, ingredient_form):
        return self.render_to_response(
            self.get_context_data(form=form,
                                  ingredient_form=ingredient_form))


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    form_class = RecipeCreateForm
    template_name = 'recipes/recipe_form.html'
    success_url = ''

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author != request.user:
            return HttpResponseForbidden()
        form = RecipeCreateForm(instance=self.object)
        ingredient_form = IngredientFormSet(instance=self.object)
        return self.render_to_response(
            self.get_context_data(form=form,
                                  ingredient_form=ingredient_form,
                                  recipe=self.object))

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = RecipeCreateForm(
            self.request.POST, self.request.FILES, instance=self.object
        )
        ingredient_form = IngredientFormSet(
            self.request.POST, instance=self.object
        )
        if (form.is_valid() and ingredient_form.is_valid()):
            return self.form_valid(form, ingredient_form)
        else:
            return self.form_invalid(form, ingredient_form)

    def form_valid(self, form, ingredient_form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        ingredient_form.instance = self.object
        ingredient_form.instance.tags.set(form.cleaned_data.get('tags'))
        ingredient_form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, ingredient_form):
        return self.render_to_response(
            self.get_context_data(form=form,
                                  ingredient_form=ingredient_form))


class FavoriteListView(LoginRequiredMixin, ListView):
    paginate_by = 9
    template_name = 'recipes/recipe_index.html'

    def get_queryset(self):
        queryset = Recipe.objects.filter(in_favorite=self.request.user)
        queryset, self.filter_tags = filter_by_tags(self.request, queryset)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Избранные рецепты'
        context['tags'] = self.filter_tags
        return context


class FollowListView(LoginRequiredMixin, ListView):
    paginate_by = 3
    template_name = 'recipes/follow_index.html'

    def get_queryset(self):
        queryset = list(self.request.user.follow.all())
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваши подписки'
        return context

src/recipes/templates/recipes/follow_index.html
{% extends 'base.html' %}
{% load static %}
{% load recipes_filter %}
{% block title %}Добро пожаловать на Anygram{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'recipes/pages/myFollow.css' %}">{% endblock %}
{% block content %}
    <div class="main__header">
        <h1 class="main__title">Мои подписки</h1>
    </div>
    <div class="card-list">
        {% for author in object_list %}
        {% get_recipes author as recipes %}
        {% recipes_count author.recipes as count %}
        <div class="card-user" data-author="{{ author.pk }}">
            <div class="card-user__header">
                <h2 class="card-user__title">{{ author.first_name }}</h2>
            </div>
            <div class="card-user__body">
                <ul class="card-user__items">
                    {% for recipe in recipes %}
                    <li class="card-user__item">
                        <div class="recipe">
                            <img src="{{ recipe.image_url }}" alt="Фото рецепта" class="recipe__image">
                            <h3 class="recipe__title">{{ recipe.title }}</h3>
                            <p class="recipe__text"><span class="icon-time"></span> {{ recipe.duration }} мин.</p>
                        </div>
                    </li>
                    {% endfor %}
                    {% if count > 0 %}
                    <li class="card-user__item">
                        <a href="{% url 'index_author' author.username %}" class="card-user__link link">Еще {{ count }} рецептов...</a>
                    </li>
                    {% elif count == 0 %}
                    <li class="card-user__item">
                        <a href="{% url 'index_author' author.username %}" class="card-user__link link">Страница автора</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            {% csrf_token %}
            <div class="card-user__footer">
                <button class="button button_style_light-blue button_size_auto active" name="subscribe">Отписаться</button>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if page_obj.has_other_pages %}
        {% include 'includes/paginator.html' with items=page_obj paginator=paginator %}
    {% endif %}

{% endblock %}
{% block scripts %}
    <script src="{% static 'recipes/js/config/config.js' %}"></script>
    <script src="{% static 'recipes/js/components/MainCards.js' %}"></script>
    <script src="{% static 'recipes/js/components/MyFollow.js' %}"></script>
    <script src="{% static 'recipes/js/components/Subscribe.js' %}"></script>
    <script src="{% static 'recipes/js/components/Header.js' %}"></script>
    <script src="{% static 'recipes/js/api/Api.js' %}"></script>
    <script src="{% static 'recipes/myFollow.js' %}"></script>
{% endblock %}

src/recipes/templates/recipes/recipe_author.html
{% extends 'base.html' %}
{% load static %}
{% load recipes_filter %}
{% block title %}{{ title }}{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'recipes/pages/index.css' %}">{% endblock %}
{% block content %}
    {% csrf_token %}
    {% include 'includes/tags_table.html' with title=title tags=tags %}
    {% if user.is_authenticated %}
    <div class="author-subscribe" data-author="{{ id }}">
        {% is_following user id as is_follow %}
        {% if is_follow %}
            <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_subscribe active" name="subscribe">Отписаться от автора</button></p>
        {% else %}
            <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Подписаться на автора</button></p>
        {% endif %}
    </div>
    {% endif %}
    <div class="card-list">
        {% for recipe in object_list %}
            {% include 'recipes/recipe_item.html' with recipe=recipe %}
        {% endfor %}
    </div>

    {% if page.has_other_pages %}
        {% include 'includes/paginator.html' with items=page paginator=paginator %}
    {% endif %}

{% endblock %}
{% block scripts %}
    <script src="{% static 'recipes/js/components/MainCards.js' %}"></script>

    <script src="{% static 'recipes/js/components/Purchases.js' %}"></script>
    <script src="{% static 'recipes/js/components/Favorites.js' %}"></script>
    <script src="{% static 'recipes/js/components/Subscribe.js' %}"></script>

    <script src="{% static 'recipes/js/config/config.js' %}"></script>
    <script src="{% static 'recipes/js/components/AuthorRecipe.js' %}"></script>
    <script src="{% static 'recipes/js/components/Header.js' %}"></script>

    <script src="{% static 'recipes/js/api/Api.js' %}"></script>
    <script src="{% static 'recipes/authorRecipe.js' %}"></script>
{% endblock %}

src/recipes/templates/recipes/recipe_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {% if request.resolver_match.url_name == 'recipe_new' %}Создание рецепта{% else %}Редактирование рецепта{% endif %}
{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'recipes/pages/form.css' %}">{% endblock %}
{% block content %}
    <div class="main__header">
        <h1 class="main__title">{% if request.resolver_match.url_name == 'recipe_new' %}Создание рецепта{% else %}Редактирование рецепта{% endif %}</h1>
    </div>
    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form__group">
                <label for="{{ form.title.id_for_label }}" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    <input type="text" id="{{ form.title.id_for_label }}" name="title" value="{{ form.title.value }}" class="form__input">
                    {% if form.title.errors %}
                        <span class="form__error" role="alert">{{ form.title.errors }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        <div class="tags__item">
                            <input type="checkbox" name="tags" id="id_tags_0" value="{{ form.tags.0.data.value }}" class="tags__checkbox tags__checkbox_style_orange" {% if form.tags.0.data.selected %}checked{% endif %}>
                            <label for="id_tags_0" class="tags__label">{{ form.tags.0.data.label }}</label>
                        </div>
                        <div class="tags__item">
                            <input type="checkbox" name="tags" id="id_tags_1" value="{{ form.tags.1.data.value }}" class="tags__checkbox tags__checkbox_style_green" {% if form.tags.1.data.selected %}checked{% endif %}>
                            <label for="id_tags_1" class="tags__label">{{ form.tags.1.data.label }}</label>
                        </div>
                        <div class="tags__item">
                            <input type="checkbox" name="tags" id="id_tags_2" value="{{ form.tags.2.data.value }}" class="tags__checkbox tags__checkbox_style_purple" {% if form.tags.2.data.selected %}checked{% endif %}>
                            <label for="id_tags_2" class="tags__label">{{ form.tags.2.data.label }}</label>
                        </div>
                    </div>
                    {% if form.tags.errors %}
                        <span class="form__error">{{ form.tags.errors }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                        <input type="hidden" id="cantidadId" class="form__input">
                    </div>
                    {{ ingredient_form.management_form }}
                    {{ ingredient_form.non_form_errors }}
                    <div class="form__field-group-ingredientes-container">
                        {% for item in recipe.recipeingredient_set.all %}
                        <div class="form__field-item-ingredient" id="ing_{{ forloop.counter0 }}">
                            <span> {{ item.ingredient.title }} {{ item.amount }} {{ item.ingredient.dimension }}</span>
                            <input type="checkbox" name="recipeingredient_set-{{ forloop.counter0 }}-DELETE" id="id_recipeingredient_set-{{ forloop.counter0 }}-DELETE" class="form__field-item-delete delete__checkbox">
                            <label for="id_recipeingredient_set-{{ forloop.counter0 }}-DELETE"></label>
                            <input id="id_recipeingredient_set-{{ forloop.counter0 }}-title" name="recipeingredient_set-{{ forloop.counter0 }}-title" type="hidden" value="{{ item.ingredient.title }}">
                            <input id="id_recipeingredient_set-{{ forloop.counter0 }}-amount" name="recipeingredient_set-{{ forloop.counter0 }}-amount" type="hidden" value="{{ item.amount }}">
                            <input id="id_recipeingredient_set-{{ forloop.counter0 }}-dimension" name="recipeingredient_set-{{ forloop.counter0 }}-dimension" type="hidden" value="{{ item.ingredient.dimension }}">
                            <input id="id_recipeingredient_set-{{ forloop.counter0 }}-ingredient" name="recipeingredient_set-{{ forloop.counter0 }}-ingredient" type="hidden" value="{{ item.ingredient.pk }}">
                            <input id="id_recipeingredient_set-{{ forloop.counter0 }}-id" name="recipeingredient_set-{{ forloop.counter0 }}-id" type="hidden" value="{{ item.pk }}">
                        </div>
                        {% endfor %}
                        <div class="form__field-item-ingredient">
                        </div>
                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    {% if form.ingredients.errors %}
                        <span class="form__error" role="alert">{{ form.ingredients.errors }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="{{ form.duration.id_for_label }}" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    <input type="text" id="id_duration" name="duration" class="form__input" value="{{ form.duration.value }}">
                    <label for="id_duration" class="form__label">минут</label>
                    {% if form.duration.errors %}
                        <span class="form__error" role="alert">{{ form.duration.errors }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <label for="{{ form.description.id_for_label }}" class="form__label">Описание</label>
                <div class="form__field-group">
                    <textarea name="description" id="id_description" rows="8" class="form__textarea">{{ form.description.value }}</textarea>
                    {% if form.description.errors %}
                        <span class="form__error" role="alert">{{ form.description.errors }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    {% if form.image.value.url is not None %}
                        <a href="{{ form.image.value.url }}">{{ form.image.value }}</a>
                    {% endif %}
                    <input type="file" name="image" id="id_image">
                    {% if form.image.errors %}
                        <span class="form__error" role="alert">{{ form.image.errors }}</span>
                    {% endif %}
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">{% if request.resolver_match.url_name == 'recipe_new' %}Создать рецепт{% else %}Изменить рецепт{% endif %}</button>
            </div>
        </form>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'recipes/js/config/config.js' %}"></script>
    <script src="{% static 'recipes/js/components/Header.js' %}"></script>
    <script src="{% static 'recipes/js/utils/debouncing.js' %}"></script>
    <script src="{% static 'recipes/js/api/Api.js' %}"></script>
    <script src="{% static 'recipes/formRecipe.js' %}"></script>
{% endblock %}

src/recipes/templates/recipes/recipe_index.html
{% extends 'base.html' %}
{% load static %}
{% load recipes_filter %}
{% block title %}{{ title }}{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'recipes/pages/index.css' %}">{% endblock %}
{% block content %}
{% csrf_token %}
    {% include 'includes/tags_table.html' with title=title tags=tags %}
    <div class="card-list">
        {% for recipe in object_list %}
            {% include 'recipes/recipe_item.html' with recipe=recipe %}
        {% endfor %}
    </div>
    {% if page_obj.has_other_pages %}
        {% include 'includes/paginator.html' with items=page_obj paginator=paginator %}
    {% endif %}

{% endblock %}
{% block scripts %}
    <script src="{% static 'recipes/js/components/MainCards.js' %}"></script>

    <script src="{% static 'recipes/js/components/Purchases.js' %}"></script>
    <script src="{% static 'recipes/js/components/Favorites.js' %}"></script>

    <script src="{% static 'recipes/js/config/config.js' %}"></script>
    <script src="{% static 'recipes/js/components/CardList.js' %}"></script>
    <script src="{% static 'recipes/js/components/Header.js' %}"></script>

    <script src="{% static 'recipes/js/api/Api.js' %}"></script>
    {% if request.resolver_match.url_name == 'index' %}
        <script src="{% static 'recipes/indexAuth.js' %}"></script>
    {% elif request.resolver_match.url_name == 'favorites' %}
        <script src="{% static 'recipes/favorite.js' %}"></script>
    {% endif %}
{% endblock %}

src/recipes/templates/recipes/recipe_item.html
{% load recipes_filter %}
<div class="card" data-id="{{ recipe.pk }}">
    <img src="{{ recipe.image_url }}" alt="Фото рецепта" class="card__image">
    <div class="card__body">
        <a class="card__title link" href="{% url 'recipe' recipe.slug %}">{{ recipe.title }}</a>
        <ul class="card__items">
            {% for tag in recipe.tags.all %}
                <li class="card__item"><span class="{{ tag.color }}">{{ tag.title }}</span></li>
            {% endfor %}
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span>{{ recipe.duration }} мин.</p>
            <p class="card__text">
                <span class="icon-user"></span>
                <a href="{% url 'index_author' recipe.author.username %}" style="color: black">{% if recipe.author.first_name %}{{ recipe.author.first_name }}{% else %}{{ recipe.author.username }}{% endif %}</a>
            </p>
        </div>
    </div>
    <div class="card__footer">
        {% recipe_in_cart recipe.pk as in_cart %}
        {% if in_cart %}
            <button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span>Рецепт добавлен</button>
        {% else %}
            <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
        {% endif %}
        {% if user.is_authenticated %}
            {% is_favorite recipe user as is_active %}
            {% if is_active %}
                <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_active"></span></button>
            {% else %}
                <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
            {% endif %}
        {% endif %}
    </div>
</div>